version: '3.1'
services:
  contas:
    build:
      context: .
    container_name: web-contas
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - DB_HOST=postgres
      - DB_NAME=contas
      - DB_USER=contas
      - DB_PASSWORD=1234
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: contas
